-- drop tables
DROP TABLE PERSON_TYPE IF EXISTS;
DROP TABLE PERSON IF EXISTS;
DROP TABLE PERSON_CONTACT IF EXISTS;



-- create tables
CREATE TABLE PERSON_TYPE(
    ID VARCHAR(40) NOT NULL,
    SHORT_CODE  VARCHAR(40) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATE DEFAULT SYSDATE,
    UPDATED_ON DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID)
);

CREATE TABLE PERSON(
    ID VARCHAR(40) NOT NULL,
    PERSON_TYPE_ID VARCHAR(40) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    ADDRESS_LINE_1 VARCHAR(100) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(20),
    GSM VARCHAR(20),
    EMAIL VARCHAR(100),
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATE DEFAULT SYSDATE,
    UPDATED_ON DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_PERSONTYPE FOREIGN KEY (PERSON_TYPE_ID) REFERENCES PERSON_TYPE(ID) ON DELETE CASCADE
);

CREATE TABLE PERSON_CONTACT(
    ID VARCHAR(40) NOT NULL,
    PERSON_ID VARCHAR(40) NOT NULL,
    TYPE  VARCHAR(20) NOT NULL,
    VALUE VARCHAR(100) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATE DEFAULT SYSDATE,
    UPDATED_ON DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSONCONTACT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE
);