-- drop tables
DROP TABLE PERSON_TYPE IF EXISTS;
DROP TABLE PERSON IF EXISTS;
DROP TABLE PERSON_CONTACT IF EXISTS;
DROP TABLE CAT IF EXISTS;
DROP TABLE CAT_PERSON IF EXISTS;
DROP TABLE CAT_PICTURE IF EXISTS;


-- create tables
CREATE TABLE PERSON_TYPE(
    ID VARCHAR(40) NOT NULL,
    SHORT_CODE  VARCHAR(40) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATETIME,
    UPDATED_ON DATETIME,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID)
);

CREATE TABLE PERSON(
    ID VARCHAR(40) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    ADDRESS_LINE_1 VARCHAR(100) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(100) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATETIME,
    UPDATED_ON DATETIME,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID)
);

CREATE TABLE PERSON_CONTACT(
    ID VARCHAR(40) NOT NULL,
    PERSON_ID VARCHAR(40) NOT NULL,
    TYPE  VARCHAR(20) NOT NULL,
    VALUE VARCHAR(100) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATETIME,
    UPDATED_ON DATETIME,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSONCONTACT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE
);

CREATE TABLE CAT(
    ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    BREED VARCHAR(40),
    YEAR_OF_BIRTH VARCHAR(4),
    GENDER VARCHAR(1) NOT NULL,
    NEUTERED TINYINT NOT NULL,
    CHIPPED TINYINT NOT NULL,
    ATTENTION VARCHAR(512),
    BEHAVIORAL VARCHAR(512),
    NUTRITION VARCHAR(512),
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATETIME,
    UPDATED_ON DATETIME,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID)
);

CREATE TABLE CAT_PERSON(
    ID VARCHAR(40) NOT NULL,
    CAT_ID VARCHAR(40) NOT NULL,
    PERSON_TYPE_ID VARCHAR(40) NOT NULL,
    PERSON_ID VARCHAR(40) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATETIME,
    UPDATED_ON DATETIME,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID)
);

CREATE TABLE CAT_PICTURE(
    ID VARCHAR(40) NOT NULL,
    CAT_ID VARCHAR(40) NOT NULL,
    DATA LONGBLOB NOT NULL,
    SIZE INTEGER NOT NULL,
    CONTENT_TYPE VARCHAR(40) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATETIME,
    UPDATED_ON DATETIME,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (ID)
);