DROP TABLE PERSON_TYPE IF EXISTS;

CREATE TABLE PERSON_TYPE(
    ID VARCHAR(40) NOT NULL PRIMARY KEY,
    SHORT_CODE  VARCHAR(40) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_ON DATE DEFAULT SYSDATE,
    UPDATED_ON DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR(40)
);